#!/usr/bin/env bash

IFS='.' read -r type name ignore <<< "${HOSTNAME}"
component="$(echo "${type}_${name}" | awk '{print toupper($0)}')"
root_pass="${component}_ROOT_PASS"
unset type name ignore component

if [[ $(/data/bin/mysql -u root --password=${!root_pass} -S /tmp/mysqld.sock \
                        -e "SELECT count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'gonano' AND ENGINE = 'MyISAM'\\G" |&
                            grep count | awk '{ print $2 }') -gt 0 ]]
then
  myisam="--lock-all-tables"
else
  myisam="--single-transaction"
fi

/data/bin/mysqldump ${myisam} --flush-privileges --all-databases --all-tablespaces \
  --add-drop-database --add-drop-table --create-options --extended-insert \
  --routines --triggers -u root --password=${!root_pass} -S /tmp/mysqld.sock
