#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

root_user = []
payload[:users].each do |user|
  if user[:username] == "root"
    root_user = user
    break
  end
end

# pipe the backup into mysql client to restore from backup
execute "restore from backup" do
  command <<-EOF
    bash -c 'ssh -o StrictHostKeyChecking=no #{payload[:warehouse][:host]} \
    "cat /data/var/db/mysql/#{payload[:warehouse][:backup_id]}.gz" \
      | gunzip \
        | /data/bin/mysql \
          -u root \
          --password=#{root_user[:password]} \
          -S /tmp/mysqld.sock
    for i in ${PIPESTATUS[@]}; do
      if [[ $i -ne 0 ]]; then
        exit $i
      fi
    done
    '
  EOF
end
