#!/usr/bin/env bash

IFS='.' read -r type name ignore <<< "${HOSTNAME}"
component="$(echo "${type}_${name}" | awk '{print toupper($0)}')"
root_pass="${component}_ROOT_PASS"
unset type name ignore component

/data/bin/mysql -u root --password=${!root_pass} -S /tmp/mysqld.sock
